version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: DietManagementDB
      MYSQL_USER: diet_user
      MYSQL_PASSWORD: test_password
    ports:
      - "3306:3306"
    networks:
      - app-network

  web:
    build:
      context: ./webAPI
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db
    networks:
      - app-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

networks:
  app-network:
    driver: bridge